-- This file is automatically generated using maintenance/generateSchemaSql.php.
-- Source: extensions/WikibaseSchema/sql/abstract/term_store.json
-- Do not modify this file directly.
-- See https://www.mediawiki.org/wiki/Manual:Schema_changes
CREATE TABLE /*_*/wbt_schema_terms (
  wbit_id BIGINT UNSIGNED AUTO_INCREMENT NOT NULL,
  wbit_schema_id INT UNSIGNED NOT NULL,
  wbit_term_in_lang_id INT UNSIGNED NOT NULL,
  INDEX wbt_schema_terms_schema_id (wbit_schema_id),
  UNIQUE INDEX wbt_schema_terms_term_in_lang_id_schema_id (
    wbit_term_in_lang_id, wbit_schema_id
  ),
  PRIMARY KEY(wbit_id)
) /*$wgDBTableOptions*/;
